### ISSUE TITLE
Discord link broken

### ISSUE THREAD

**Issue by panosru** [luchina-gabriel/BASE-EFI-INTEL-DESKTOP-13THGEN-14THGEN-RAPTOR-LAKE-PUBLIC#1]
Hi, the discord link isn't working in the description...

**Comment by luchina-gabriel** [comment]
Aqui abriu normalmente. Por favor, envie a tela do erro e me informe qual o seu usuário do Discord.

**Comment by panosru** [comment]
It seems that my ad blocker was blocking the URL, I'm sorry for the false alarm! 

PS: I don't speak Portuguese :D

**Comment by panosru** [comment]
Ah no, sorry, it opens Discord but not the channel to download the BASE EFI.

**Comment by luchina-gabriel** [comment]
Se você não enxerga a sala para download da EFI-BASE, é porque seu usuário não está conectado no seu YouTube, lembrando que esta sala estará disponível somente à membros do canal.
